#!/bin/sh /etc/rc.common
# Copyright (C) 2020 Martin Pecka, 3-clause BSD license (see LICENSE file)

START=95

USE_PROCD=1

SYSLOG_FILE=/var/log/ppp
PARSED_FILE=/var/log/ppp.login

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/parse_pptp_log.py "${SYSLOG_FILE}" >> "${PARSED_FILE}"
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_close_instance
}

reload_service()
{
  stop
	start
}

